#!/usr/bin/env python3
"""
Redmine note sync for autoagents — posts a Textile (.red) closing summary
when a CLOSED task is archived.

Env (autoagents/.env):
  REDMINE_URL       — e.g. https://redmine.amvara.de
  REDMINE_API_KEY   — X-Redmine-API-Key
  REDMINE_ISSUE_ID  — target Redmine issue (integer)

Uses stdlib urllib only (no httpx).
"""
from __future__ import annotations

import json
import os
import re
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from typing import Optional

NOTE_AUTHOR = "km0-opencloud autoagents"
NOTES_DIR = "/root/redminenotes"


class RedmineError(Exception):
    """Redmine API call failed."""


class IssueNotFound(RedmineError):
    """Redmine issue does not exist."""


def add_redmine_note(
    base_url: str,
    api_key: str,
    issue_id: int,
    notes: str,
    *,
    timeout: float = 60.0,
) -> None:
    """PUT /issues/{id}.json with a journal note. Raises on HTTP errors."""
    url = f"{base_url.rstrip('/')}/issues/{issue_id}.json"
    payload = json.dumps({"issue": {"notes": notes}}).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=payload,
        method="PUT",
        headers={
            "X-Redmine-API-Key": api_key,
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            if resp.status >= 400:
                raise RedmineError(f"Redmine PUT issue failed: {resp.status}")
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")[:500]
        if exc.code == 404:
            raise IssueNotFound(f"Issue #{issue_id} not found") from exc
        raise RedmineError(
            f"Redmine PUT issue failed: {exc.code} {body}"
        ) from exc
    except urllib.error.URLError as exc:
        raise RedmineError(f"Redmine request failed: {exc.reason}") from exc


def get_redmine_config() -> tuple[str, str, int] | None:
    """Return (base_url, api_key, issue_id) when fully configured, else None."""
    base_url = os.environ.get("REDMINE_URL", "").strip()
    api_key = os.environ.get("REDMINE_API_KEY", "").strip()
    issue_raw = os.environ.get("REDMINE_ISSUE_ID", "").strip()
    if not base_url or not api_key or not issue_raw:
        return None
    try:
        issue_id = int(issue_raw)
    except ValueError:
        print(
            f"  warn: REDMINE_ISSUE_ID must be an integer, got {issue_raw!r}",
            file=sys.stderr,
        )
        return None
    return base_url, api_key, issue_id


def extract_closing_summary(task_text: str) -> str:
    m = re.search(
        r"## Closing summary \(TOP\)\s*\n(.*?)\n---",
        task_text,
        re.DOTALL | re.IGNORECASE,
    )
    if m:
        return m.group(1).strip()
    return ""


def _parse_summary_bullets(summary: str) -> dict[str, str]:
    fields: dict[str, str] = {}
    for line in summary.splitlines():
        m = re.match(r"^-\s+\*\*(.+?):\*\*\s*(.*)$", line.strip())
        if m:
            fields[m.group(1).strip()] = m.group(2).strip()
    return fields



def format_closing_note_textile(
    *,
    task_basename: str,
    github_issue_num: Optional[int],
    summary_text: str,
    repo: str = "AMVARA-CONSULTING/km0-opencloud",
) -> str:
    """Build English Textile note body (.red rules — no Markdown fences)."""
    fields = _parse_summary_bullets(summary_text)
    closed_at = fields.get("Closed at (UTC)", "")
    if not closed_at:
        closed_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    gh_ref: str
    if github_issue_num is None:
        gh_ref = "n/a"
    elif github_issue_num == 0:
        gh_ref = "none (no GitHub issue)"
    else:
        gh_ref = f"#{github_issue_num}"
    lines = [
        "h2. Autoagents task completed",
        "",
        f"*Date:* {closed_at}",
        f"*Repository:* @{repo}@",
        f"*Task file:* @autoagents/tasks/{task_basename}@",
        f"*GitHub issue:* {gh_ref}",
        "",
        "---",
        "",
        "h3. Summary",
        "",
    ]

    label_map = (
        ("What happened", "What happened"),
        ("What was done", "What was done"),
        ("What was tested", "What was tested"),
        ("Why closed", "Why closed"),
    )
    for key, heading in label_map:
        value = fields.get(key, "")
        if value:
            lines.append(f"* *{heading}:* {value}")
        else:
            lines.append(f"* *{heading}:* _(not recorded)_")

    if summary_text and not fields:
        lines.append("")
        lines.append("> Raw closing summary:")
        for raw_line in summary_text.splitlines():
            stripped = raw_line.strip()
            if stripped:
                lines.append(f"> {stripped}")

    lines.extend(
        [
            "",
            "---",
            "",
            f"_Auto-generated by {NOTE_AUTHOR}. Textile (.red) format; English prose._",
        ]
    )
    return "\n".join(lines)


def _note_body_with_author(*, author_label: str, formatted: str) -> str:
    return f"*Posted by:* {author_label}\n\n{formatted}"


def save_note_copy(basename: str, body: str) -> str:
    os.makedirs(NOTES_DIR, exist_ok=True)
    stem = re.sub(r"\.md$", "", basename)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    path = os.path.join(NOTES_DIR, f"autoagents-{stem}-{stamp}.red")
    with open(path, "w", encoding="utf-8") as f:
        f.write(body)
    return path


def issue_num_from_closed_basename(basename: str) -> Optional[int]:
    m = re.match(r"^CLOSED-(\d+)-", basename)
    return int(m.group(1)) if m else None


def notify_redmine(task_path: str) -> bool:
    """Post formatted closing note to Redmine. Returns True on success or skip."""
    cfg = get_redmine_config()
    if cfg is None:
        print("  skip Redmine — REDMINE_URL, REDMINE_API_KEY, or REDMINE_ISSUE_ID unset")
        return True

    base_url, api_key, issue_id = cfg
    bn = os.path.basename(task_path)
    gh_num = issue_num_from_closed_basename(bn)

    with open(task_path, encoding="utf-8") as f:
        task_text = f.read()

    summary = extract_closing_summary(task_text)
    formatted = format_closing_note_textile(
        task_basename=bn,
        github_issue_num=gh_num,
        summary_text=summary,
    )
    posted = _note_body_with_author(author_label=NOTE_AUTHOR, formatted=formatted)

    copy_path = save_note_copy(bn, formatted)
    print(f"  Redmine: saved .red copy at {copy_path}")

    try:
        add_redmine_note(base_url, api_key, issue_id, posted)
    except IssueNotFound as exc:
        print(f"  error: {exc}", file=sys.stderr)
        return False
    except RedmineError as exc:
        print(f"  error: {exc}", file=sys.stderr)
        return False

    issue_url = f"{base_url.rstrip('/')}/issues/{issue_id}"
    print(f"  Redmine: posted note to issue #{issue_id} ({issue_url})")
    return True


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(
            "Usage:\n"
            "  redmine_sync.py note <path/to/CLOSED-....md>\n"
            "  redmine_sync.py test [--dry-run]",
            file=sys.stderr,
        )
        sys.exit(1)

    cmd = sys.argv[1]

    if cmd == "note" and len(sys.argv) == 3:
        ok = notify_redmine(sys.argv[2])
        sys.exit(0 if ok else 1)

    if cmd == "test":
        dry_run = "--dry-run" in sys.argv[2:]
        cfg = get_redmine_config()
        if cfg is None:
            print(
                "REDMINE_URL, REDMINE_API_KEY, and REDMINE_ISSUE_ID must be set",
                file=sys.stderr,
            )
            sys.exit(1)
        base_url, api_key, issue_id = cfg
        sample = format_closing_note_textile(
            task_basename="CLOSED-0-20260527-1200-redmine-sync-test.md",
            github_issue_num=0,
            summary_text=(
                "- **What happened:** Integration test for Redmine note posting.\n"
                "- **What was done:** Verified add_redmine_note and Textile formatter.\n"
                "- **What was tested:** PUT /issues/{id}.json with API key.\n"
                "- **Why closed:** Smoke test passed.\n"
                "- **Closed at (UTC):** "
                + datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")
            ),
        )
        posted = _note_body_with_author(author_label=NOTE_AUTHOR, formatted=sample)
        print("--- formatted note ---")
        print(posted)
        print("--- end ---")
        if dry_run:
            print("Dry run — not posted.")
            sys.exit(0)
        try:
            add_redmine_note(base_url, api_key, issue_id, posted)
        except (IssueNotFound, RedmineError) as exc:
            print(f"error: {exc}", file=sys.stderr)
            sys.exit(1)
        print(f"Posted test note to {base_url}/issues/{issue_id}")
        sys.exit(0)

    print("Unknown command", file=sys.stderr)
    sys.exit(1)
